version: '3'

services:
  prometheus:
    image: prom/prometheus:latest         #repo/image:tag
    ports:
      - "9090:9090"                       #hostport:containerport
    volumes:
      - ./prometheus:/etc/prometheus      #host address: container workdir address
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus


  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app.py:/app/app.py
