channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.2.2
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.2.1
  - lz4==3.1.3
  - numpy==1.24.4
  - packaging==23.2
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.3.1
  - scipy==1.11.3
name: mlflow-env
